import type { DefaultTheme, UserConfig } from 'vitepress'
import { DOCS_VERSION, REPO, sharedConfig } from './shared.mts'

/**
 * The versioned half: the guided path, deployed to /docs/<version>/.
 *
 * The Dokka reference is generated by Gradle and copied in beside this output at /api/, so links to
 * it are absolute paths rather than VitePress routes.
 */
const base = `/docs/${DOCS_VERSION}/`

export const docsConfig: UserConfig<DefaultTheme.Config> = {
  ...sharedConfig,
  base,
  outDir: `../dist/docs/${DOCS_VERSION}`,
  srcExclude: ['news/**', 'index.md'],
  themeConfig: {
    ...sharedConfig.themeConfig,
    nav: [
      { text: 'Learn', link: '/learn/' },
      { text: 'Reference', link: `${base}api/`, target: '_self' },
      {
        text: DOCS_VERSION,
        items: [
          { text: 'All versions', link: '/versions', target: '_self' },
          { text: 'Changelog', link: `${REPO}/blob/main/CHANGELOG.md` },
        ],
      },
    ],
    sidebar: {
      '/learn/': [
        {
          text: 'Tutorial',
          collapsed: false,
          items: [
            { text: 'Introduction', link: '/learn/' },
            { text: '1. Your first CLI', link: '/learn/tutorial/your-first-cli' },
          ],
        },
        {
          text: 'How-to guides',
          collapsed: false,
          items: [{ text: 'Overview', link: '/learn/how-to/' }],
        },
        {
          text: 'Explanation',
          collapsed: false,
          items: [{ text: 'Overview', link: '/learn/explanation/' }],
        },
      ],
    },
    editLink: {
      pattern: `${REPO}/edit/main/site/:path`,
      text: 'Edit this page on GitHub',
    },
  },
}
