package org.draftcode.argot.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ARRAY
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.joinToCode
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo

/** Fully-qualified names of the engine types/functions referenced by generated code. */
private const val ENGINE_PACKAGE = "org.draftcode.argot"

private val COMMAND_SPEC = ClassName(ENGINE_PACKAGE, "CommandSpec")
private val OPTION_SPEC = ClassName(ENGINE_PACKAGE, "OptionSpec")
private val FLAG_SPEC = ClassName(ENGINE_PACKAGE, "FlagSpec")
private val ARGUMENT_SPEC = ClassName(ENGINE_PACKAGE, "ArgumentSpec")
private val ARGOT_ENGINE = ClassName(ENGINE_PACKAGE, "ArgotEngine")

private val STRING_CONVERTER = MemberName(ENGINE_PACKAGE, "StringConverter")
private val INT_CONVERTER = MemberName(ENGINE_PACKAGE, "IntConverter")
private val LONG_CONVERTER = MemberName(ENGINE_PACKAGE, "LongConverter")
private val DOUBLE_CONVERTER = MemberName(ENGINE_PACKAGE, "DoubleConverter")
private val BOOLEAN_CONVERTER = MemberName(ENGINE_PACKAGE, "BooleanConverter")
private val ENUM_CONVERTER = MemberName(ENGINE_PACKAGE, "enumConverter")

/** True when [type]'s declaration is `kotlin.collections.List`. */
internal fun isListType(type: KSType): Boolean =
    type.declaration.qualifiedName?.asString() == "kotlin.collections.List"

/** The element type of a `List<T>`, or null if it cannot be resolved. */
internal fun listElementType(type: KSType): KSType? =
    type.arguments.firstOrNull()?.type?.resolve()

/**
 * Maps a supported parameter type to the [CodeBlock] that constructs its [Converter], or null if
 * the type is unsupported. Enums map to a reflection-free `enumConverter<E>()` call.
 */
internal fun resolveConverter(type: KSType): CodeBlock? {
    val declaration = type.declaration
    return when (declaration.qualifiedName?.asString()) {
        "kotlin.String" -> CodeBlock.of("%M", STRING_CONVERTER)
        "kotlin.Int" -> CodeBlock.of("%M", INT_CONVERTER)
        "kotlin.Long" -> CodeBlock.of("%M", LONG_CONVERTER)
        "kotlin.Double" -> CodeBlock.of("%M", DOUBLE_CONVERTER)
        "kotlin.Boolean" -> CodeBlock.of("%M", BOOLEAN_CONVERTER)
        else -> if ((declaration as? KSClassDeclaration)?.classKind == ClassKind.ENUM_CLASS) {
            CodeBlock.of("%M<%T>()", ENUM_CONVERTER, type.makeNotNullable().toTypeName())
        } else {
            null
        }
    }
}

/**
 * Emits the generated `parse<ClassName>(argv): ClassName` function for one [Command] class, using
 * KotlinPoet. Output is deterministic (declaration order preserved) and carries a "do not edit"
 * header.
 */
internal class CommandCodeGenerator(
    private val codeGenerator: CodeGenerator,
    @Suppress("unused") private val logger: KSPLogger,
) {
    fun generate(
        cls: KSClassDeclaration,
        programName: String,
        description: String,
        params: List<ResolvedParam>,
        internalVisibility: Boolean,
    ) {
        val packageName = cls.packageName.asString()
        val functionName = "parse${cls.simpleName.asString()}"
        val target = cls.toClassName()

        val body = CodeBlock.builder()
        body.add("val spec = %T(\n", COMMAND_SPEC).indent()
        body.add("programName = %S,\n", programName)
        if (description.isNotEmpty()) body.add("description = %S,\n", description)
        body.add("params = listOf(\n").indent()
        params.forEach { body.add("%L,\n", specFor(it)) }
        body.unindent().add("),\n")
        body.unindent().add(")\n")
        body.add("val parsed = %T.parse(spec, argv)\n", ARGOT_ENGINE)
        body.add("return %T(\n", target).indent()
        params.forEach { body.add("%N = %L,\n", it.paramName, extractionFor(it)) }
        body.unindent().add(")\n")

        val function = FunSpec.builder(functionName)
            .addKdoc(
                "Parses [argv] into a [%T] and returns it.\n\n" +
                    "Generated by Argot from the @Command annotation. Do not edit.",
                target,
            )
            // Match the @Command class's visibility so a public parser never exposes an internal type.
            .addModifiers(if (internalVisibility) KModifier.INTERNAL else KModifier.PUBLIC)
            .addParameter("argv", ARRAY.parameterizedBy(STRING))
            .returns(target)
            .addCode(body.build())
            .build()

        FileSpec.builder(packageName, functionName)
            .addFileComment("Generated by Argot. Do not edit.")
            .addFunction(function)
            .build()
            .writeTo(codeGenerator, aggregating = false, originatingKSFiles = listOfNotNull(cls.containingFile))
    }

    private fun specFor(param: ResolvedParam): CodeBlock = when (param.kind) {
        ParamKind.OPTION -> CodeBlock.builder().apply {
            add("%T(names = %L, converter = %L", OPTION_SPEC, namesList(param.names), param.converter)
            if (param.help.isNotEmpty()) add(", help = %S", param.help)
            when {
                param.multiple -> add(", multiple = true, required = false")
                param.required -> add(", required = true")
                param.default != null -> add(", default = %L.convert(%S)", param.converter, param.default)
            }
            add(")")
        }.build()

        ParamKind.FLAG -> CodeBlock.builder().apply {
            add("%T(names = %L", FLAG_SPEC, namesList(param.names))
            if (param.help.isNotEmpty()) add(", help = %S", param.help)
            add(")")
        }.build()

        ParamKind.ARGUMENT -> CodeBlock.builder().apply {
            add("%T(name = %S, converter = %L", ARGUMENT_SPEC, param.paramName, param.converter)
            if (param.help.isNotEmpty()) add(", help = %S", param.help)
            when {
                param.multiple -> add(", multiple = true, required = false")
                !param.required -> add(", required = false")
            }
            add(")")
        }.build()
    }

    private fun extractionFor(param: ResolvedParam): CodeBlock {
        val key = param.lookupKey
        return when {
            param.kind == ParamKind.FLAG -> CodeBlock.of("parsed.flag(%S)", key)
            param.multiple -> CodeBlock.of("parsed.list(%S)", key)
            param.required || param.default != null -> CodeBlock.of("parsed.value(%S)", key)
            else -> CodeBlock.of("parsed.valueOrNull(%S)", key)
        }
    }

    private fun namesList(names: List<String>): CodeBlock =
        names.map { CodeBlock.of("%S", it) }.joinToCode(prefix = "listOf(", suffix = ")")
}
